### ISSUE TITLE
Non-helpful message "Xxx.method should be after Xxx.None"

### ISSUE THREAD

**Issue by bitphage** [best-doctor/flake8-class-attributes-order#19] opened 2020-05-18 11:44 UTC
I've got an error on a module:

```
viz/amount.py:30:5: CCE001 Amount.asset should be after Amount.None
```

And it's like "Wtf? What None? I don't have `def None`"

Can be reproduced with https://github.com/VIZ-Blockchain/viz-python-lib/blob/master/viz/amount.py

**Comment by Melevir** [comment] 2020-05-18 14:49
The issue is resolved in v0.1.1. I've just released new version.

**Closed as completed by Melevir** 2020-05-18 14:49 UTC
Labels: enhancement
